### ISSUE TITLE
Practica 7

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/cs-equipo-gregorio-8us#1]
[Practica7  Reconocimiento de imagenes.pdf](https://github.com/SistemasTecTlaxiaco/cs-equipo-gregorio-8us/files/15192903/Practica7.Reconocimiento.de.imagenes.pdf)

**Comment by salathiel1999** [comment]
20%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
